# Generated by Django 3.0 on 2020-11-16 04:09

import Documents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер документа')),
                ('name', models.CharField(max_length=120, verbose_name='Название документа')),
                ('body', models.TextField(verbose_name='Описание документа')),
                ('slug', models.SlugField(max_length=150)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('purposes', models.CharField(choices=[('На утверждение', 'На утверждение'), ('На согласование', 'На согласование'), ('К исполнению', 'К исполнению'), ('К сведенью', 'К сведенью')], default='На утверждение', max_length=20, verbose_name='Назначение')),
                ('status', models.CharField(choices=[('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено'), ('В процессе', 'В процессе')], default='В процессе', max_length=20, verbose_name='Статус')),
                ('type', models.CharField(choices=[('Документ', 'Документ'), ('Заявление', 'Заявление'), ('Рапорт', 'Рапорт')], default='Документ', max_length=20, verbose_name='Тип документа')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='User.Profile', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MovementOfDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(default='В ожидании', max_length=30, verbose_name='Движение')),
                ('view', models.CharField(choices=[('Просмотрено', 'Просмотрено'), ('Не просмотрено', 'Не просмотрено')], default='Не просмотрено', max_length=30, verbose_name='Просмотр')),
                ('status', models.CharField(choices=[('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено'), ('В процессе', 'В процессе')], default='В процессе', max_length=20, verbose_name='Статус документа')),
                ('is_main_person', models.BooleanField(default=False, verbose_name='Ответственный сотрудник')),
                ('is_redirect', models.BooleanField(default=False, verbose_name='Перенаправлен сотруднику')),
                ('is_open_reply', models.BooleanField(default=True, verbose_name='Можеть ли отправитьответь')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='Documents.Document')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='User.Profile')),
            ],
            options={
                'verbose_name': 'Движение документа',
                'verbose_name_plural': 'Движения документов',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ReplyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(choices=[('Утверждаю', 'Утверждаю'), ('Согласен', 'Согласен'), ('Не согласен', 'Не согласен'), ('Принято к исполнению', 'Принято к исполнению'), ('Принято к сведению', 'Принято к сведению'), ('В ожидании', 'В ожидании')], default='В ожидании', max_length=30, verbose_name='Движение')),
                ('status', models.CharField(choices=[('Принят', 'Принят'), ('Не принят', 'Не принят'), ('В ожидании', 'В ожидании')], default='В ожидании', max_length=20, verbose_name='Статус ответа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Documents.Document')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Documents.MovementOfDocument')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='FileReplyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Documents.models.upload_to_reply_file, verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Documents.ReplyDocument')),
            ],
            options={
                'verbose_name': 'Файл ответа',
                'verbose_name_plural': 'Файлы ответа',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='FileDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=Documents.models.upload_to_file, verbose_name='Файлы')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Documents.Document')),
            ],
            options={
                'verbose_name': 'Файл документа',
                'verbose_name_plural': 'Файлы документов',
                'ordering': ('-created',),
            },
        ),
    ]
