# Generated by Django 3.0 on 2020-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='itn',
            field=models.CharField(max_length=70, unique=True, verbose_name='Идентификационный номер налогоплательщика (сокращенно ИНН)'),
        ),
    ]
