# Generated by Django 3.0 on 2020-11-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20201116_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='abbreviated_name',
            field=models.CharField(max_length=50, verbose_name='Сокращенное название'),
        ),
        migrations.AlterField(
            model_name='position',
            name='doc_name',
            field=models.CharField(max_length=150, verbose_name='Название для заявление или рапорта'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
